name: Bug Report
description: The plugin shows unexpected or undesired behaviour.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        > Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Try to give a clear and concise description of what the bug is.
      placeholder: |
        How do you trigger this bug? What did you expect to happen?
    validations:
      required: true

  - type: input
    id: cypress-version
    attributes:
      label: Cypress version
      description: "Which `cypress` version are you using?"
      placeholder: 13.2.0
    validations:
      required: true

  - type: input
    id: cypress-xray-plugin-version
    attributes:
      label: Plugin version
      description: "Which `cypress-xray-plugin` version are you using?"
      placeholder: 5.2.1
    validations:
      required: true

  - type: dropdown
    id: jira-type
    attributes:
      label: Jira/Xray type
      description: Which Jira/Xray environment are you using?
      options:
        - Cloud
        - Server
    validations:
      required: true

  - type: textarea
    id: cypress-config
    attributes:
      label: Configuration
      description: |
        Sharing your cypress configuration will help tracking down and resolving the bug as fast as possible. It is usually stored in files called `cypress.config.js` or `cypress.config.ts`. Make sure not to paste sensitive data such as passwords, secret tokens and URLs.
      placeholder: |
        This will be formatted automatically, so don't add backticks. Just paste the code as is.
      render: ts
    validations:
      required: false

  - type: checkboxes
    id: credentials-acknowledgement
    attributes:
      label: "Acknowledgements"
      options:
        - label: I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
          required: true
        - label: I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
          required: true
        - label: I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.
          required: true
